# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
commands:
  print_pipeline_id:
    description: "A very simple command for demonstration purposes"
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID} 
jobs:
  myjob:
    docker:
      - image: circleci/node:13.8.0
    steps:
      -  print_pipeline_id
workflows:
  myworkflow:
    jobs:
      - myjob